### ISSUE TITLE
timeframe for catkinization

### ISSUE THREAD

**Issue by piyushk** [ros-controls/ros_control#39]
I just wanted to check if there are any plans to catkinize this stack soon.

Thanks!

**Comment by jbohren** [comment]
We could also make it a hybrid catkin rosbuild package, and that won't
break anyone.

**Comment by adolfo-rt** [comment]
I agree that catkinization should be an important item in the ros_control todo list, but I second @jbohren's suggestion of supporting both catkin/rosbuild for some time.

I am currently developing against ROS Fuerte, and have no immediate plans of migrating to more recent ROS distros (or taking over the catkinization effort), so backwards compatibility with rosbuild remains important for the time being.

**Comment by jbohren** [comment]
Take a look at GSCam: https://github.com/ros-drivers/gscam for an example
of how to do this.

On Tue, May 28, 2013 at 6:55 AM, Adolfo Rodriguez Tsouroukdissian <
notifications@github.com> wrote:

> I agree that catkinization should be an important item in the ros_control
> todo list, but I second @jbohren https://github.com/jbohren's
> suggestion of supporting both catkin/rosbuild for some time.
> 
> I am currently developing against ROS Fuerte, and have no immediate plans
> of migrating to more recent ROS distros (or taking over the catkinization
> effort), so backwards compatibility with rosbuild remains important for the
> time being.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/willowgarage/ros_control/issues/39#issuecomment-18543464
> .

## 

Jonathan Bohren
Laboratory for Computational Sensing and Robotics
http://dscl.lcsr.jhu.edu/People/JonathanBohren

**Comment by davetcoleman** [comment]
I think it would be best if we made a 'hydro-devel' branch for the catkin version, and have the hydro debs no longer use a stack. We would still of course have the rosbuild stuff for previous version.

Also, what is the status of the 'master' branch - can it be removed in favor of a particular ROS distro branch? Is most of the development going on still in the 'fuerte' branch?

I'm making tutorials right now that will be teaching ROS users how to use ros_control with Gazebo (based on Jonathan's work) and it requires catkin, so getting an official branch of this soon would be nice for that. See:
http://gazebosim.org/wiki/Tutorials/1.9/Using_A_URDF_In_Gazebo

Update: I've split the tutorial, the ros_control section is now at:
http://gazebosim.org/wiki/Tutorials/1.9/ROS_Control_with_Gazebo

Thanks!

**Comment by jbohren** [comment]
Since a few people who are involved in the development are using ros_control with Fuerte, I'm going to modify the catkin branch to use a hybrid buildsystem, and then we can use that for Fuerte/Groovy/Hydro development. 

@wmeeusse @vpradeep07 @sachinchitta Would such a change be ok to merge in?

**Comment by wmeeusse** [comment]
Releasing the hybrid catkin/rosbuild build system into fuerte is a fine thing to do; just make sure the changes are limited to the build system only.   At this point we have tree different (api incompatible) branches: fuerte, groovy and master.  The latest and greatest features can at this point only get released into hydro, but we can safely backport the buildsystem changes to fuerte/groovy.

**Comment by jbohren** [comment]
Cool, thanks Wim!

@adolfo-rt What branch of ros_control are you using at PAL?

**Comment by adolfo-rt** [comment]
I'm developing against the master branch, which seems to be the latest and greatest (all other branches are +100 commits behind). Since my setup is very particular (Fuerte + latest changes), I would greatly appreciate maintaining rosbuild compatibility in the hydro-devel branch.

**Comment by jbohren** [comment]
Exactly, I'm just wondering what the "incompatibilities" are that Win was
taking about. I guess he just means that the api changed?

That's good, though. It means the master branch can be given a hybrid
buildsystem and still work with Fuerte.

**Comment by wmeeusse** [comment]
@jbohren the incompatibilities are indeed api changes.  Since ros_control is still under development and pre-1.0, we're releasing our latest and greatest version into ros, every time a new ros distro comes out.  The only constraint we have is that once we've released in a ros distro, we can't change the api any more in that same distro. But of course, the next ros distro can have a new api again.  The only exception for this rule are the relatime_tools and control_toolbox packages, which are stable and are used by other stable stacks. 

So whenever the lockdown for hydro comes by, we'll branch off master and create a hydro-dev branch for releases into hydro.

**Comment by adolfo-rt** [comment]
Two questions on releasing into a ROS distro:
- I understand that the API can't be broken in the same ROS distro. This does not come in conflict with backwards compatible API additions, correct?, ie. the equivalent of a minor version increment in [semantic versioning](http://semver.org/).
- If the ros_control feature set that we want to make available in Hydro is not ready for the initial release date, is it acceptable to add ros_control at a later date?. It seems that the Hydro cycle will be [~9-10 months long](http://ros-users.122217.n3.nabble.com/ROS-Release-Timeline-td4020078.html), so whatever version we decide to stick with, will stay for a while.

**Comment by yamokosk** [comment]
We are also using the master branch. But over the next 2 weeks we will be jumping our development to either hydro or groovy.

Sent from my iPhone

On Jun 6, 2013, at 9:21 PM, "Jonathan Bohren" <notifications@github.com<mailto:notifications@github.com>> wrote:

Cool, thanks Wim!

@adolfo-rthttps://github.com/adolfo-rt What branch of ros_control are you using at PAL?

**Comment by davetcoleman** [comment]
We can follow MoveIt's example and release into ROS disto/bloom but still not move out of beta. This would allow us to make breaking API changes as needed but give us the convenience of a build system and pre-built packages. As long as you document and make very clear the code changes needed between versions, I don't think this is a problem.

**Comment by wmeeusse** [comment]
@adolfo-rt Correct, backwards compatible api additions are okay for pre-1.0 stacks. Instead of delaying the entire stack, we can make a release with the stable feature set only, and then add components to the release as they stabilize. Some packages in the stack (realtime_tools and controller_toolbox) have to get released early on because the pr2 stacks depend on it, and I think the core api's of the stack are also stable enough to get release. But I can imagine we delay e.g. some of the transmission code. 

@davetcoleman I've personally been very frustrated with MoveIt breaking my code every time I pull in new Debian packages. I do see the tradeoff you're talking about, but I much rather give the users of the Debian packages a stable api, and have the developers compile the stack from source. If a cutting edge user is really interested in the latest api, he/she probably doesn't mind compiling from source.  But a less advanced user might appreciate the ability to build on Debian packages that remain backward compatible api's.

**Comment by jbohren** [comment]
My PRs [1] [2] have been updated with a hybrid (catkin+rosbuild)
buildsystem.

[1] https://github.com/willowgarage/ros_control/pull/40
[2] https://github.com/willowgarage/ros_controllers/pull/8

-j

On Mon, Jun 10, 2013 at 11:55 PM, wmeeusse notifications@github.com wrote:

> @adolfo-rt https://github.com/adolfo-rt Correct, backwards compatible
> api additions are okay for pre-1.0 stacks. Instead of delaying the entire
> stack, we can make a release with the stable feature set only, and then add
> components to the release as they stabilize. Some packages in the stack
> (realtime_tools and controller_toolbox) have to get released early on
> because the pr2 stacks depend on it, and I think the core api's of the
> stack are also stable enough to get release. But I can imagine we delay
> e.g. some of the transmission code.
> 
> @davetcoleman https://github.com/davetcoleman I've personally been very
> frustrated with MoveIt breaking my code every time I pull in new Debian
> packages. I do see the tradeoff you're talking about, but I much rather
> give the users of the Debian packages a stable api, and have the developers
> compile the stack from source. If a cutting edge user is really interested
> in the latest api, he/she probably doesn't mind compiling from source. But
> a less advanced user might appreciate the ability to build on Debian
> packages that remain backward compatible api's.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/willowgarage/ros_control/issues/39#issuecomment-19241145
> .

## 

Jonathan Bohren
Laboratory for Computational Sensing and Robotics
http://dscl.lcsr.jhu.edu/People/JonathanBohren

**Comment by wmeeusse** [comment]
@jbohren Awesome, thanks Jon!

**Comment by davetcoleman** [comment]
This is great, thanks so much!

**Comment by adolfo-rt** [comment]
I see that ros_control no longer has a CMakeLists.txt nor a stack.xml at the top level, but ros_controllers does. We should harmonize the two repos in this respect.

As a rosbuild user, I prefer to keep these files, (or at least stack.xml) as they allow to call rosmake on stacks. Any objection from the catkin side?.

**Comment by davetcoleman** [comment]
It shouldn't break anything catkin, it just hurts a little on the inside to see them hanging around :)

**Comment by ahendrix** [comment]
The Hydro beta freeze is June 29th, in 5 days; I need a release before then so that I can proceed with PR2 releases.

If I don't get any objections, I will release the current master branch of ros_control into Hydro tomorrow, as version 0.1.

**Comment by jbohren** [comment]
I, for one plan to continue to build it from source.

**Comment by adolfo-rt** [comment]
> I, for one plan to continue to build it from source.

Me too, as I'm actively developing, and not in Hydro.

**Comment by davetcoleman** [comment]
We need Hydro debians for Gazebo's ros_control bindings. Also, could this be released into Groovy as well?

**Comment by jbohren** [comment]
(by which @davetcoleman means we need hydro debians of ros_control & ros_controllers so that gazebo's ros_control bindings can also be made into debians)

@wmeeusse thoughts on releasing into groovy?

**Comment by wmeeusse** [comment]
Both ros_control and ros_controllers have already been released into Groovy, with an older api. We can't break that api, but we can release a version of ros_control_gazebo into groovy that works with that older api.

**Comment by mikeferguson** [comment]
@wmeeusse They were released as 0.0.1, correct? Many (if not most) packages released with <0.5.0 have often had API-breaking changes. The old stack policy page (http://www.ros.org/wiki/StackVersionPolicy) doesn't even mention "stable API" until 0.4.0 and above. I suppose you'd want to evaluate how many users would be effected by breaking the API in Groovy, but there is no rule (even in the REPs) that says a pre-0.4 release needs to have a stable API.

@ahendrix Along the same lines though, the old stack version policy did require that >=1.0 components depend only on stable APIs -- so you might reconsider porting PR2 to this right now, as it's not clear even the API going into Hydro is going to be stable.

**Comment by ahendrix** [comment]
@mikeferguson The PR2 is _ALREADY_ ported to this, and released more or less without my consent... grumble... grumble... I just have to live with it and push things forward as best I can.

**Comment by mikeferguson** [comment]
@ahendrix Ah.. OK

**Comment by wmeeusse** [comment]
@mikeferguson Within the model of the stack policy, I'd argue we're currently still pre-tick-tock, but at the point where we're keeping a stable api within each ros release. I guess this puts us somewhere at the 0.4.x level. Our version number doesn't reflect that, but it seems silly to just bump the version up to correspond to the policy.  So I don't think we already need to go through deprecation tick-tock cycles, but I very much want to keep the api stable within each ros release cycle.  In between cycles I'm fine with breaking changes. At this point our api also affects the binary compatibility of the pr2 controllers, so that's another reason to not change our api within a ros release cycle.

**Comment by ahendrix** [comment]
Released version 0.4.0 into Hydro.

There's still time during the Hydro beta freeze over the next month for bug fixes and minor API changes.
